window.PortfolioSites = [
  {
    slug: "mingxuan-profile",
    title: "张明轩个人主页",
    kind: "个人网站",
    style: "深色名片",
    href: "mingxuan-profile/",
    image: "mingxuan-profile.jpg",
    accentName: "深蓝与香槟金",
    cta: "联系合作",
    secondary: "看作品",
    kicker: "产品设计师个人站",
    headline: "一屏说清楚我是谁。",
    intro: "参考高端个人名片站结构，集中展示介绍、作品、服务和联系入口。",
    dials: "变化 6，动效 4，密度 5",
    facts: ["个人主页", "作品入口", "服务说明", "联系转化"],
    palette: ["#07111d", "#142234", "#d4a85d", "#eef3f6"]
  },
  {
    slug: "neon-foundry",
    title: "Neon Foundry",
    kind: "创意工作室",
    style: "暗黑实验",
    href: "neon-foundry/",
    image: "neon-foundry.jpg",
    accentName: "青蓝与朱红",
    cta: "看作品",
    secondary: "看方法",
    kicker: "动态视觉工作室",
    headline: "会动的品牌系统。",
    intro: "为发布片、空间活动和动态品牌世界设计的高对比工作室网站。",
    dials: "变化 9，动效 8，密度 3",
    facts: ["发布影片", "空间活动", "动态识别", "整合传播"],
    palette: ["#0c1517", "#20c7d4", "#e84838", "#f1f7f7"]
  },
  {
    slug: "lumen-atelier",
    title: "Lumen Atelier",
    kind: "高端产品",
    style: "简约贵气",
    href: "lumen-atelier/",
    image: "lumen-atelier.jpg",
    accentName: "冷银金属",
    cta: "预约试香",
    secondary: "查看香调",
    kicker: "建筑感香氛品牌",
    headline: "像设计空间一样设计气味。",
    intro: "为虚构香氛品牌打造的克制冷感产品页，安静、干净、有价格感。",
    dials: "变化 6，动效 4，密度 2",
    facts: ["香氛系列", "材质叙事", "试香预约", "零售页面"],
    palette: ["#eef1f1", "#5f676e", "#b8c2cc", "#171c20"]
  },
  {
    slug: "pomelo-pop",
    title: "Pomelo Pop",
    kind: "消费应用",
    style: "可爱鲜艳",
    href: "pomelo-pop/",
    image: "pomelo-pop.jpg",
    accentName: "柚子珊瑚红",
    cta: "试一节课",
    secondary: "看模块",
    kicker: "创意学习应用",
    headline: "小课程，大色彩。",
    intro: "为少儿学习产品设计的明亮触感网站，好玩但不廉价。",
    dials: "变化 8，动效 7，密度 4",
    facts: ["学习应用", "家长页面", "产品发布", "趣味视觉"],
    palette: ["#fff2d7", "#f15f5f", "#1f8f65", "#ffc840"]
  },
  {
    slug: "northline-works",
    title: "Northline Works",
    kind: "企业服务",
    style: "稳重案例",
    href: "northline-works/",
    image: "northline-works.jpg",
    accentName: "运营绿",
    cta: "预约诊断",
    secondary: "看案例",
    kicker: "运营咨询服务",
    headline: "为复杂运营做一个可信页面。",
    intro: "面向物流、采购和流程改造的企业服务案例页，克制、清晰、能建立信任。",
    dials: "变化 5，动效 4，密度 5",
    facts: ["服务案例", "采购信任", "高层汇报", "线索表单"],
    palette: ["#eef3ef", "#16352e", "#2d8b68", "#23333b"]
  },
  {
    slug: "voltage-room",
    title: "Voltage Room",
    kind: "活动落地页",
    style: "高能酷炫",
    href: "voltage-room/",
    image: "voltage-room.jpg",
    accentName: "酸性绿",
    cta: "购买通票",
    secondary: "看阵容",
    kicker: "夜间设计节",
    headline: "先击中，再说明。",
    intro: "为灯光装置、演出和夜间创意文化打造的沉浸式活动页面。",
    dials: "变化 9，动效 8，密度 4",
    facts: ["售票发布", "阵容展示", "场地叙事", "赞助页面"],
    palette: ["#110a13", "#d92ba3", "#c8df2b", "#f5f0f5"]
  },
  {
    slug: "quiet-harbor",
    title: "Quiet Harbor",
    kind: "酒店民宿",
    style: "安静高级",
    href: "quiet-harbor/",
    image: "quiet-harbor.jpg",
    accentName: "海岸蓝",
    cta: "查看入住",
    secondary: "看房型",
    kicker: "海岸阅读度假地",
    headline: "一种更安静的目的地。",
    intro: "为海岸阅读度假地打造的高级民宿网站，安静、通透、有停留感。",
    dials: "变化 6，动效 4，密度 3",
    facts: ["度假网站", "房型叙事", "预订路径", "编辑气质"],
    palette: ["#edf4f7", "#233641", "#6aa7b8", "#d7d0c7"]
  }
];
